### ISSUE TITLE
Object explorer is still white

### ISSUE THREAD

**Issue by cath1ynn** [aplab/darkyog#2]
When I applied the dark theme, the Object explorer on the left hand side is still white. See image below.

![sqlyog_2017-12-18_10-05-57](https://user-images.githubusercontent.com/17055570/34085144-d0756236-e3db-11e7-9922-c99a67465786.png)

Also, the link to download PHP is incorrect. The correct link is 
http://windows.php.net/downloads/releases/php-7.1.12-nts-Win32-VC14-x64.zip

It's probably easier to just direct people to http://windows.php.net/download and tell them which file to download.

**Comment by cath1ynn** [comment]
Actually, disregard my issue. I've figured out a way to change it.

**Comment by aplab** [comment]
README.md updated
