### ISSUE TITLE
Multiple errors when running darkyog.bat

### ISSUE THREAD

**Issue by J0rdyV** [aplab/darkyog#4]
I get this error when i run darkyog.bat from a cmd window without admin access.
Php version php-7.2.7-nts-Win32-VC15-x64 under C:\php\ `contents of zip file`
C:\Users\ ******\Downloads\darkyog-master\src\Darkyog.php is in that folder.

Username is edited out :)

Full error message:
`
Warning: file(C:\Users\****\AppData\Roaming\SQLyog\sqlyog.ini): failed to open stream: No such file or directory in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 67
Warning: parse_ini_file(C:\Users\******\AppData\Roaming\SQLyog\sqlyog.ini): failed to open stream: No such file or directory in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 68
Warning: reset() expects parameter 1 to be array, boolean given in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 75
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: Invalid argument supplied for foreach() in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 171
Warning: mkdir(): No such file or directory in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 121
Warning: copy(C:\Users\******\AppData\Roaming\SQLyog/themes/Dark.xml): failed to open stream: No such file or directory in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 122
Warning: join(): Invalid arguments passed in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 187
Warning: file_put_contents(C:\Users\******\AppData\Roaming\SQLyog\sqlyog.ini): failed to open stream: No such file or directory in C:\Users\******\Downloads\darkyog-master\src\Darkyog.php on line 187
 bytes written
`

**Comment by aplab** [comment]
In file: darkyog/src/Darkyog.php

public function __construct()
    {
        $this->user = get_current_user();

change to

public function __construct()
    {
        $this->user = 'your_username';

explicitly replace with the username where SQLYog data is located:

C:\Users\your_username\AppData\Roaming\SQLYog
